resources:
  - name: my_Git_Repository
    type: GitRepo
    configuration:
      gitProvider: xraysample_git
      path: yosi-q/jfrog-pipeline-sample
      branches:
        include: main

pipelines:
  - name: sample_pipeline
    steps:
    - name: step_1
      type: Bash
      configuration:
        inputResources:
          - name: my_Git_Repository     # Trigger execution on code commit
      execution:
        onExecute:
          - echo "Hello World!"
    
    - name: step_2
      type: Bash
      configuration:
        inputSteps:
          - name: step_1               # Execute this step after the prior step
      execution:
        onExecute:
          - echo "Goodbye World!"