resources:
  - name: my_Git_Repository
    type: GitRepo
    configuration:
      gitProvider: xraysample_git
      path: yosi-q/jfrog-pipeline-sample
      branches:
        include: main

  - name: mvn_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: satoytestingfree
      buildName: pipeline_build
      buildNumber: 1   

pipelines:
  - name: sample_pipeline
    configuration:
      jfrogCliVersion: 2
    steps:
    - name: step_init
      type: Bash
      configuration:
        inputResources:
          - name: my_Git_Repository     # Trigger execution on code commit
      execution:
        onExecute:
          - echo "Hello World!"
    
    - name: step_build
      type: MvnBuild
      configuration:
        resolverSnapshotRepo: xraysample
        resolverReleaseRepo: xraysample
        deployerSnapshotRepo: xraysample
        deployerReleaseRepo: xraysample
        integrations:
          - name: satoytestingfree
        inputResources:
          - name: my_Git_Repository     # Trigger execution on code commit
        inputSteps:
          - name: step_init               # Execute this step after the prior step
      execution:
        onStart:
          - echo "Preparing for work..."
        onSuccess:
          - echo "Job well done!"
        onFailure:
          - echo "uh oh, something went wrong"
        onComplete:                                  #always
          - echo "Cleaning up some stuff"

    - name: publish_build_info
      type: PublishBuildInfo
      configuration:
        inputSteps: 
          - name: step_build
        outputResources: 
          - name: mvn_build_info

    - name: step_final
      type: Bash
      configuration:
        inputSteps:
          - name: publish_build_info               # Execute this step after the prior step
      execution:
        onExecute:
          - echo "Goodbye World!"